// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CogvisAI Alarms API
 *
 * API for managing alarms and visualizations from cogvisAI sensors.
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface { 
	AuthLoginPost(http.ResponseWriter, *http.Request)
	AlarmsGet(http.ResponseWriter, *http.Request)
	AlarmsPost(http.ResponseWriter, *http.Request)
	AlarmsAlarmIdGet(http.ResponseWriter, *http.Request)
}


// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface { 
	AuthLoginPost(context.Context, LoginRequest) (ImplResponse, error)
	AlarmsGet(context.Context, int32, int32, string, string) (ImplResponse, error)
	AlarmsPost(context.Context, Alarm) (ImplResponse, error)
	AlarmsAlarmIdGet(context.Context, string) (ImplResponse, error)
}
