// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CogvisAI Alarms API
 *
 * API for managing alarms and visualizations from cogvisAI sensors.
 *
 * API version: 1.0.0
 */

package openapi


import (
	"time"
)



type Alarm struct {

	Id int64 `json:"id,omitempty"`

	SensorId int64 `json:"sensorId,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`

	Type string `json:"type,omitempty"`

	Visualizations []Visualization `json:"visualizations,omitempty"`
}

// AssertAlarmRequired checks if the required fields are not zero-ed
func AssertAlarmRequired(obj Alarm) error {
	for _, el := range obj.Visualizations {
		if err := AssertVisualizationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAlarmConstraints checks if the values respects the defined constraints
func AssertAlarmConstraints(obj Alarm) error {
	for _, el := range obj.Visualizations {
		if err := AssertVisualizationConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
