// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CogvisAI Alarms API
 *
 * API for managing alarms and visualizations from cogvisAI sensors.
 *
 * API version: 1.0.0
 */

package openapi




type LoginResponse struct {

	Token string `json:"token,omitempty"`
}

// AssertLoginResponseRequired checks if the required fields are not zero-ed
func AssertLoginResponseRequired(obj LoginResponse) error {
	return nil
}

// AssertLoginResponseConstraints checks if the values respects the defined constraints
func AssertLoginResponseConstraints(obj LoginResponse) error {
	return nil
}
