// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CogvisAI Alarms API
 *
 * API for managing alarms and visualizations from cogvisAI sensors.
 *
 * API version: 1.0.0
 */

package openapi




type Visualization struct {

	Id int64 `json:"id,omitempty"`

	AlarmId int64 `json:"alarmId,omitempty"`

	ImageBase64 string `json:"imageBase64,omitempty"`
}

// AssertVisualizationRequired checks if the required fields are not zero-ed
func AssertVisualizationRequired(obj Visualization) error {
	return nil
}

// AssertVisualizationConstraints checks if the values respects the defined constraints
func AssertVisualizationConstraints(obj Visualization) error {
	return nil
}
