// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CogvisAI Alarms API
 *
 * API for managing alarms and visualizations from cogvisAI sensors.
 *
 * API version: 1.0.0
 */

package openapi




type AlarmsGet200Response struct {

	Alarms []Alarm `json:"alarms,omitempty"`

	Total int32 `json:"total,omitempty"`
}

// AssertAlarmsGet200ResponseRequired checks if the required fields are not zero-ed
func AssertAlarmsGet200ResponseRequired(obj AlarmsGet200Response) error {
	for _, el := range obj.Alarms {
		if err := AssertAlarmRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAlarmsGet200ResponseConstraints checks if the values respects the defined constraints
func AssertAlarmsGet200ResponseConstraints(obj AlarmsGet200Response) error {
	for _, el := range obj.Alarms {
		if err := AssertAlarmConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
